### PR TITLE
Added new components for Outfit build

### PR DESCRIPTION
**Pull request by Luke82601**

### CODE REVIEW

**Review by BrentonHershner — CHANGES_REQUESTED** [review]
I don't see any changes to the actual page. I don't think the outfit component is being rendered...

**Comment by Luke82601** [comment]
Nothing is rendering yet, I just created the components at this point

**Comment by BrentonHershner** [comment]
> Nothing is rendering yet, I just created the components at this point

I'm not trying to be a dick, but how does one effectively review something that can't be seen and isn't being tested?

**Comment by Luke82601** [comment]
I suppose you have a point, however, the way I see it, if there's nothing to test, there's nothing it can break. But if you want me to wait til I have some content that's fine with me

**Pull request closed without merging**
